on:
  push:
    branches:
      - master
  pull_request:
      types: [closed]
      branches:
          - master

name: Fetch updated manga
jobs:
  build:
    name: Fetch updated manga
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run fetchupdates
      - run: npx typedoc -out bundles/docs
        continue-on-error: true

      - name: Deploy Sources
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: bundles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
